Algoritmo "ENQUANTOC"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda Nalon
// Descrição   : Letra C
// Autor(a)    : Lara dos Santos Dourado
// Data atual  : 12/12/2024
Var
// Seção de Declarações das variáveis 
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
numero <- 11

enquanto numero >= 1 faca
    numero <- numero - 1
    escreval(numero)
    
fimenquanto



Fimalgoritmo